[package]
name = "mirrorx_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] }
bincode = "1.3.3"
bytes = "1.1.0"
futures = "0.3.21"
anyhow = "1.0.56"
tokio-rustls = { version = "0.23.3", features = ["logging"] }
rustls = { version = "0.20.4", features = ["logging"] }
rand = "0.8.5"
dashmap = "5.2.0"
once_cell = "1.10.0"
ctrlc = { version = "3.2.2", features = ["termination"] }
