[package]
name = "mirrorx_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
redis = { version = "0.21.5", features = [
    "r2d2",
    "tokio-comp",
    "connection-manager",
] }
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.14"
lazy_static = "1.4.0"
ed25519-compact = { version = "1.0.11", features = ["pem"] }
base64 = "0.13.0"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] }
bincode = "1.3.3"
bytes = "1.1.0"
hex = "0.4.3"
futures = "0.3.21"
anyhow = "1.0.56"
num_enum = "0.5.7"
downcast-rs = "1.2.0"
tower = { version = "0.4.12", features = ["full"] }
tokio-tower = "0.6.0"
tokio-rustls = { version = "0.23.3", features = ["logging"] }
rustls = { version = "0.20.4", features = ["logging"] }
webpki-roots = "0.22.2"
rustls-pemfile = "0.3.0"
rand = "0.8.5"
dashmap = "5.2.0"
async-trait = "0.1.53"
