[package]
name = "endpoints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.17"
tokio = { version = "1.19.2", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["full"] }
bincode = "1.3.3"
bytes = "1.1.0"
futures = "0.3.21"
anyhow = "1.0.58"
rand = "0.8.5"
dashmap = "5.3.4"
once_cell = "1.12.0"
toml = "0.5.9"
fxhash = "0.2.1"
moka = { version = "0.8.5", features = ["future"] }
